---
name: CI

on:
  push:
  pull_request:

concurrency:
  group: ${{ github.workflow }}

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    container:
      image: alpine/curl:8.4.0
    services:
        keycloak:
            image: dvrbanec/keycloak-dev:latest
            env: 
              KEYCLOAK_ADMIN: admin
              KEYCLOAK_ADMIN_PASSWORD: testing1   
              KC_HOSTNAME: keycloak  
              KC_HTTP_ENABLED: true
            ports:
              - 8080:8080
            options: >-
              --health-cmd "curl -f http://localhost:8080/auth/realms/master"
              --health-interval 5s
              --health-timeout 10s
              --health-retries 10
              --health-start-period 30s

    steps:
      - name: Curl Keycloak
        run: |
          curl -vLI http://keycloak:8080/
